#! /bin/sh

cd `dirname $0`

if [ ! -d "vendor" ]; then
  mkdir vendor
fi

if [ ! -d "vendor/aurora.js" ]; then
  git clone https://github.com/JensNockert/aurora.js.git vendor/aurora.js
fi

if [ ! -d "vendor/import" ]; then
  git clone https://github.com/devongovett/import.git vendor/import
fi

cd vendor/aurora.js && git pull && cd `dirname $0`
cd vendor/import    && git pull && cd `dirname $0`
